version: '3.7'
services:
  ### Databases
  buffer_db:
    image: redis:6.0
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis:/data
    networks:
      default:
        aliases:
          - redis
      lightshield:
        aliases:
          - redis
    restart: always

  proxy:
    image: lightshield/proxy:${TAG}
    networks:
      default:
        aliases:
          - proxy
    restart: always
    env_file:
      - secrets.env
    environment:
      - LIMIT_SHARE=100
    logging:
      driver: "json-file"
      options:
       max-file: "5"
       max-size: "10m"

volumes:
  redis:
    name: lightshield_buffer

networks:
  lightshield:
    external: true
  default:
    external:
      name: lightshield
