version: '2.3'
services:

  proxy:
    build:
      dockerfile: Dockerfile
      context: services/proxy
    environment:
      - SERVER=${SERVER}
    env_file:
      - secrets.env
    restart: always

  league_updater:
    build:
      dockerfile: Dockerfile
      context: services/league_updater
    environment:
      - SERVER=${SERVER}
    external_links:
      - riotapi_rabbitmq:rabbitmq
    links:
      - proxy:proxy
    depends_on:
      - riotapi_rabbitmq
    restart: always

  summoner_id_updater:
    build:
      dockerfile: Dockerfile
      context: services/summoner_id_updater
    environment:
      - SERVER=${SERVER}
    links:
      - redis_summoner_id:redis
      - proxy:proxy
    external_links:
      - riotapi_rabbitmq:rabbitmq
    depends_on:
      - redis_summoner_id
      - riotapi_rabbitmq
    restart: always

  redis_summoner_id:
    build:
      context: databases/redis
      dockerfile: Dockerfile
    restart: always

  match_history_updater:
    build:
      dockerfile: Dockerfile
      context: services/match_history_updater
    environment:
      - SERVER=${SERVER}
    links:
      - redis_match_history:redis
      - proxy:proxy
    external_links:
      - riotapi_rabbitmq:rabbitmq
    depends_on:
      - redis_match_history
      - riotapi_rabbitmq
    restart: always

  redis_match_history:
    build:
      context: databases/redis
      dockerfile: Dockerfile
    restart: always

  match_updater:
    build:
      dockerfile: Dockerfile
      context: services/match_updater
    environment:
      - SERVER=${SERVER}
    links:
      - redis_match:redis
      - proxy:proxy
    external_links:
      - riotapi_rabbitmq:rabbitmq
    depends_on:
      - redis_match
      - riotapi_rabbitmq
    restart: always

  redis_match:
    build:
      context: databases/redis
      dockerfile: Dockerfile
    restart: always

  db_worker:
    build:
      dockerfile: Dockerfile
      context: services/db_worker/
    environment:
      - SERVER=${SERVER}
    external_links:
      - riotapi_postgres:postres
      - riotapi_rabbitmq:rabbitmq
    depends_on:
      - riotapi_rabbitmq
      - riotapi_postgres
    restart: always

volumes:
  redis_summoner:
  redis_match_history:
  redis_match:

networks:
  default:
    external:
      name: riot_api
