version: '2.3'
services:

  proxy:
    build:
      dockerfile: Dockerfile
      context: services/proxy
    container_name: ${COMPOSE_PROJECT_NAME}_proxy
    environment:
      - SERVER=${SERVER}
    env_file:
      - secrets.env
    restart: always
    volumes:
        - ./logs/:/project/logs/
        - ./configs/:/project/configs/

### Services

  structural_creator:
    build:
      dockerfile: Dockerfile
      context: services/structural_creator
    container_name: ${COMPOSE_PROJECT_NAME}_structural_creator
    environment:
      - SERVER=${SERVER}
    external_links:
      - lightshield_rabbitmq:rabbitmq

  league_rankings:
    hostname: league_rankings
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/league_rankings
    environment:
      - SERVER=${SERVER}
      - UPDATE_INTERVAL=1
      - WORKER=5
      - STREAM=RANKED
      - MAX_TASK_BUFFER=1000
    links:
      - proxy:proxy
    external_links:
      - lightshield_rabbitmq:rabbitmq
    depends_on:
      - structural_creator
    restart: always
    volumes:
      - ./sqlite/:/project/sqlite/
      - ./configs/:/project/configs/

  summoner_ids:  # SI
    hostname: summoner_ids
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/summoner_ids
    environment:
      - SERVER=${SERVER}
      - WORKER=35
      - MAX_TASK_BUFFER=1000
      - STREAM=SUMMONER
    volumes:
      - ./sqlite/:/project/sqlite/
    links:
      - proxy:proxy
    external_links:
      - lightshield_rabbitmq:rabbitmq
    depends_on:
      - structural_creator
    restart: always

  match_history:  # MH
    hostname: match_history
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/match_history
    environment:
      - SERVER=${SERVER}
      - WORKER=10
      - MATCHES_TO_UPDATE=10
      - TIME_LIMIT=1595401200
      - MAX_TASK_BUFFER=2000
      - STREAM=HISTORY
    volumes:
      - ./sqlite/:/project/sqlite/
    links:
      - proxy:proxy
    external_links:
      - lightshield_rabbitmq:rabbitmq
    depends_on:
      - structural_creator
    restart: always

  match_details:  # MD
    hostname: match_details
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/match_details
    environment:
      - SERVER=${SERVER}
      - WORKER=45
      - MAX_TASK_BUFFER=200
      - STREAM=DETAILS
    volumes:
      - ./sqlite/:/project/sqlite/
    links:
      - proxy:proxy
    external_links:
      - lightshield_rabbitmq:rabbitmq
    depends_on:
      - structural_creator
    restart: always

  processor:
    container_name: ${COMPOSE_PROJECT_NAME}_processor
    build:
      dockerfile: Dockerfile
      context: services/processor
    environment:
      - SERVER=${SERVER}
    external_links:
      - lightshield_rabbitmq:rabbitmq
    links:
      - persistant_db:postgres
    depends_on:
      - structural_creator
    restart: always

  persistant_db:
    container_name: ${COMPOSE_PROJECT_NAME}_persistant_db
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always


volumes:
  postgres:
    name: ${SERVER}_lightshield


networks:
  default:
    external:
      name: lightshield
