version: '2.3'
services:

  rabbitmq:
    container_name: lightshield_rabbitmq
    image: rabbitmq:management
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: always

volumes:
  rabbitmq:

networks:
  default:
    external:
      name: lightshield
