version: '3.7'
services:
  ### Services

  league_rankings:
    hostname: league_rankings
    build:
      dockerfile: Dockerfile
      context: services/league_rankings
    image: lightshield_league_rankings
    environment:
      - SERVER=${SERVER}
      - UPDATE_INTERVAL=1
      - WORKER=5
    restart: always
    volumes:
      - ranking_progress:/project/configs/

  summoner_ids_manager:
    hostname: summoner_ids
    build:
      dockerfile: Dockerfile
      context: services/summoner_ids_manager
    image: lightshield_summoner_ids_manager
    environment:
      - SERVER=${SERVER}

  summoner_ids: # SI
    hostname: summoner_ids
    build:
      dockerfile: Dockerfile
      context: services/summoner_ids
    image: lightshield_summoner_ids
    environment:
      - SERVER=${SERVER}
    volumes:
      - /backup
    restart: always

  match_history_manager:
    hostname: match_history
    environment:
      - MIN_MATCHES=20
      - SERVER=${SERVER}
    build:
      dockerfile: Dockerfile
      context: services/match_history_manager
    image: lightshield_match_history_manager

  match_history: # MH
    hostname: match_history
    build:
      dockerfile: Dockerfile
      context: services/match_history
    image: lightshield_match_history
    environment:
      - SERVER=${SERVER}
      - QUEUES=420
    volumes:
      - /backup
    restart: always

  match_details_manager:
    hostname: match_details
    build:
      dockerfile: Dockerfile
      context: services/match_details_manager
    image: lightshield_match_details_manager
    environment:
      - LIMIT=5000
      - SERVER=${SERVER}


  match_details: # MH
    hostname: match_details
    build:
      dockerfile: Dockerfile
      context: services/match_details
    image: lightshield_match_details
    environment:
      - SERVER=${SERVER}
      - QUEUES=420
      - BATCH_SIZE=30
    restart: always

volumes:
  postgres:
    name: ${SERVER}_lightshield_persistent
  redis:
    name: ${SERVER}_lightshield_buffer
  ranking_progress:
    name: ${SERVER}_ranking_progress


networks:
  default:
    external:
      name: lightshield


x-disabled:

  buffer_db:
    image: redis:6.0
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis:/data
    networks:
      default:
        aliases:
          - redis
    restart: always


  match_details: # MD
    hostname: match_details
    image: python:3.8
    build:
      dockerfile: Dockerfile
      context: services/match_details
    environment:
      - SERVER=${SERVER}
      - WORKER=45
      - MAX_TASK_BUFFER=1000
      - STREAM=DETAILS
    volumes:
      - /backup
    links:
      - persistent_db:postgres
    external_links:
      - lightshield_rabbitmq:rabbitmq
    restart: always

  processor_match:
    image: python:3.8
    build:
      dockerfile: Dockerfile
      context: services/processor_match
    environment:
      - SERVER=${SERVER}
      - STREAM="placeholder"
      - MAX_TASK_BUFFER=111
    external_links:
      - lightshield_rabbitmq:rabbitmq
    links:
      - persistent_db:postgres
    volumes:
      - ./lol_dto:/project/lol_dto
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  processor_summoner:
    image: python:3.8
    build:
      dockerfile: Dockerfile
      context: services/processor_summoner
    environment:
      - SERVER=${SERVER}
    external_links:
      - lightshield_rabbitmq:rabbitmq
    links:
      - persistent_db:postgres
    volumes:
      - ./lol_dto:/project/lol_dto
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
