version: '2.3'
services:
### Services

  league_rankings:
    hostname: league_rankings
    mem_limit: 150m
    cpus: 0.15
    build:
      dockerfile: Dockerfile
      context: services/league_rankings
    environment:
      - SERVER=${SERVER}
      - UPDATE_INTERVAL=1
      - WORKER=5
    links:
      - persistent_db:postgres
    restart: always
    volumes:
      - ranking_progress:/project/configs/

  summoner_ids_manager:
    hostname: summoner_ids
    mem_limit: 100m
    cpus: 0.1
    build:
      dockerfile: Dockerfile
      context: services/summoner_ids_manager
    links:
      - buffer_db:redis
      - persistent_db:postgres

  summoner_ids: # SI
    hostname: summoner_ids
    mem_limit: 100m
    cpus: 0.15
    build:
      dockerfile: Dockerfile
      context: services/summoner_ids
    environment:
      - SERVER=${SERVER}
    volumes:
      - /backup
    links:
      - buffer_db:redis
      - persistent_db:postgres
    restart: always

  match_history_manager:
    hostname: match_history
    mem_limit: 100m
    cpus: 0.1
    build:
      dockerfile: Dockerfile
      context: services/match_history_manager
    links:
      - buffer_db:redis
      - persistent_db:postgres

  match_history: # MH
    hostname: match_history
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/match_history
    environment:
      - SERVER=${SERVER}
      - QUEUES=420
    volumes:
      - /backup
    links:
      - buffer_db:redis
      - persistent_db:postgres
    restart: always

  match_details:  # MD
    hostname: match_details
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/match_details
    environment:
      - SERVER=${SERVER}
      - WORKER=45
      - MAX_TASK_BUFFER=1000
      - STREAM=DETAILS
    volumes:
      - /backup
    links:
      - persistent_db:postgres
    external_links:
      - lightshield_rabbitmq:rabbitmq
    restart: always

  processor_match:
    build:
      dockerfile: Dockerfile
      context: services/processor_match
    environment:
      - SERVER=${SERVER}
      - STREAM="placeholder"
      - MAX_TASK_BUFFER=111
    external_links:
      - lightshield_rabbitmq:rabbitmq
    links:
      - persistent_db:postgres
    volumes:
      - ./lol_dto:/project/lol_dto
    restart: always
    logging:
      driver: "json-file"
      options:
       max-file: "5"
       max-size: "10m"

  processor_summoner:
    build:
      dockerfile: Dockerfile
      context: services/processor_summoner
    environment:
      - SERVER=${SERVER}
    external_links:
      - lightshield_rabbitmq:rabbitmq
    links:
      - persistent_db:postgres
    volumes:
      - ./lol_dto:/project/lol_dto
    restart: always
    logging:
      driver: "json-file"
      options:
       max-file: "5"
       max-size: "10m"

  persistent_db:
    container_name: ${COMPOSE_PROJECT_NAME}_persistent_db
    build:
      context: postgres
      dockerfile: Dockerfile
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always

  buffer_db:
    image: redis:6.0
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis:/data
    restart: always

volumes:
  postgres:
    name: ${SERVER}_lightshield_persistent
  redis:
    name: ${SERVER}_lightshield_buffer
  ranking_progress:
    name: ${SERVER}_ranking_progress


networks:
  default:
    external:
      name: lightshield
