version: '3.7'
services:
  ### Databases
  buffer_db:
    image: redis:6.0
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis:/data
    networks:
      default:
        aliases:
          - redis
      lightshield:
        aliases:
          - redis
    restart: always

volumes:
  redis:
    name: lightshield_buffer

networks:
  lightshield:
    external: true
  default:
    external:
      name: lightshield
