version: '2.3'
services:

  rabbitmq:
    hostname: rabbitmq
    container_name: lightshield_rabbitmq
    image: rabbitmq:3-management
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: always
    

volumes:
  rabbitmq:

networks:
  default:
    external:
      name: lightshield
