version: '2.3'
services:

  proxy:
    build:
      dockerfile: Dockerfile
      context: services/proxy
    container_name: ${COMPOSE_PROJECT_NAME}_proxy
    environment:
      - SERVER=${SERVER}
    env_file:
      - secrets.env
    restart: always
    volumes:
        - ./logs/:/project/logs/
        - ./configs/:/project/configs/

### Services

  league_rankings:
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/league_rankings
    environment:
      - SERVER=${SERVER}
      - UPDATE_INTERVAL=${LR_UPDATE_INTERVAL}
      - WORKER=${LR_WORKER}
      - REQUIRED_SUBSCRIBER=${LR_REQUIRED_SUBSCRIBER}
    links:
      - proxy:proxy
      - league_rankings_redis:redis
    restart: always
    volumes:
      - ./configs/:/project/configs/

  summoner_ids:
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/summoner_ids
    environment:
      - SERVER=${SERVER}
      - WORKER=${SI_WORKER}
      - REQUIRED_SUBSCRIBER=${SI_REQUIRED_SUBSCRIBER}
      - MAX_TASK_BUFFER=${SI_MAX_TASK_BUFFER}
    links:
      - summoner_ids_redis:redis
      - proxy:proxy
      - league_rankings:provider
    restart: always

  match_history:
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/match_history
    environment:
      - SERVER=${SERVER}
      - WORKER=${MH_WORKER}
      - MATCHES_TO_UPDATE=${MH_MATCHES_TO_UPDATE}
      - TIME_LIMIT=${TIME_LIMIT}
      - MAX_TASK_BUFFER=${MH_MAX_TASK_BUFFER}
      - REQUIRED_SUBSCRIBER=${MH_REQUIRED_SUBSCRIBER}
    links:
      - match_history_redis:redis
      - proxy:proxy
      - summoner_ids:provider
    restart: always

  match_details:
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/match_details
    environment:
      - SERVER=${SERVER}
      - WORKER=${MD_WORKER}
      - MAX_TASK_BUFFER=${MD_MAX_TASK_BUFFER}
      - REQUIRED_SUBSCRIBER=${MD_REQUIRED_SUBSCRIBER}
    volumes:
      - ./sqlite/{SERVER}_match_details.db:/project/sqlite3.db
    links:
      - match_details_redis:redis
      - proxy:proxy
      - match_history:provider
    external_links:
      - lightshield_postgres:postres
    restart: always

### Database Connector

  database_connector_summoner:
    mem_limit: 250m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/database_connector_summoner/
    environment:
      - SERVER=${SERVER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - MAX_TASK_BUFFER=500  # TODO: Move to ENV file
    external_links:
      - lightshield_postgres:postres
    links:
      - summoner_ids:provider
      - database_connector_summoner_redis:redis
    restart: always

  database_connector_match_details:
    mem_limit: 250m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/database_connector_match_details/
    environment:
      - SERVER=${SERVER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - MAX_TASK_BUFFER=500  # TODO: Move to ENV file
    external_links:
      - lightshield_postgres:postres
    links:
      - match_details:provider
      - database_connector_match_details_redis:redis
    restart: always


### REDIS Databases

  league_rankings_redis:
    mem_limit: 250m
    cpus: 0.25
    build:
      context: databases/redis
      dockerfile: Dockerfile
    volumes:
      - league_rankings:/data/
    restart: always

  summoner_ids_redis:
    mem_limit: 250m
    cpus: 0.25
    build:
      context: databases/redis
      dockerfile: Dockerfile
    volumes:
        - summoner_ids:/data/
    restart: always


  match_history_redis:
    mem_limit: 250m
    cpus: 0.25
    build:
      context: databases/redis
      dockerfile: Dockerfile
    volumes:
        - match_history:/data/
    restart: always

  match_details_redis:
    mem_limit: 250m
    cpus: 0.25
    build:
      context: databases/redis
      dockerfile: Dockerfile
    volumes:
        - match_details:/data/
    restart: always

  database_connector_summoner_redis:
    mem_limit: 50m
    cpus: 0.1
    build:
      context: databases/redis
      dockerfile: Dockerfile
    volumes:
      - database_connector_summoner:/data/
    restart: always

  database_connector_match_details_redis:
    mem_limit: 50m
    cpus: 0.1
    build:
      context: databases/redis
      dockerfile: Dockerfile
    volumes:
      - database_connector_match_details:/data/
    restart: always

volumes:
  league_rankings:
    name: ${SERVER}_league_rankins
  summoner_ids:
    name: ${SERVER}_summoner_ids
  match_history:
    name: ${SERVER}_match_history
  match_details:
    name: ${SERVER}_match_details
  database_connector_summoner:
    name: ${SERVER}_database_connector_summoner
  database_connector_match_details:
    name: ${SERVER}_database_connector_match_details

networks:
  default:
    external:
      name: lightshield
