version: '3.7'
services:
  ### Databases
  buffer_db:
    image: redis:6.0
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis:/data
    networks:
      default:
        aliases:
          - redis
      lightshield:
        aliases:
          - redis
    restart: always

  status_page:
    image: lightshield_status_page
    build:
      dockerfile: Dockerfile
      context: global/status_page/backend
    restart: always
    environment:
      - SERVER=NA1,EUW1,KR
    env_file:
      - secrets.env
    ports:
      - 8003:8000

volumes:
  redis:
    name: lightshield_buffer

networks:
  lightshield:
    external: true
  default:
    external:
      name: lightshield
