version: '2.3'
services:

  rabbitmq:
    container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
    image: launcher.gcr.io/google/rabbitmq3
    mem_limit: 4g
    cpus: 4
    hostname: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: always

  postgres:
    cpus: 1
    mem_limit: 1g
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    build:
      dockerfile: Dockerfile
      context: databases/postgres/
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
        - 127.0.0.1:5432:5432
    restart: always

volumes:
  rabbitmq:
  postgres:

networks:
  default:
    external:
      name: riot_api
