version: '2.3'
services:

  proxy:
    build:
      dockerfile: Dockerfile
      context: services/proxy_3
    environment:
      - SERVER=${SERVER}
    env_file:
      - secrets.env

  league_updater:
    build:
      dockerfile: Dockerfile
      context: services/league_updater
    environment:
      - SERVER=${SERVER}
    external_links:
      - riotapi_rabbitmq:rabbitmq
    links:
      - proxy:proxy

  summoner_id_updater:
    build:
      dockerfile: Dockerfile
      context: services/summoner_id_updater
    environment:
      - SERVER=${SERVER}
    links:
      - redis_summoner_id:redis
      - proxy:proxy
    external_links:
      - riotapi_rabbitmq:rabbitmq

  redis_summoner_id:
    build:
      context: databases/redis
      dockerfile: Dockerfile


  match_history_updater:
    build:
      dockerfile: Dockerfile
      context: services/match_history_updater
    environment:
      - SERVER=${SERVER}
    links:
      - redis_match_history:redis
      - proxy:proxy
    external_links:
      - riotapi_rabbitmq:rabbitmq

  redis_match_history:
    build:
      context: databases/redis
      dockerfile: Dockerfile

  match_updater:
    build:
      dockerfile: Dockerfile
      context: services/match_updater
    environment:
      - SERVER=${SERVER}
    links:
      - redis_match:redis
      - proxy:proxy
    external_links:
      - riotapi_rabbitmq:rabbitmq

  redis_match:
    build:
      context: databases/redis
      dockerfile: Dockerfile

  db_worker:
    build:
      dockerfile: Dockerfile
      context: services/db_worker/
    environment:
      - SERVER=${SERVER}
    external_links:
      - postgres:postres
      - riotapi_rabbitmq:rabbitmq

volumes:
  redis_summoner:
  redis_match_history:
  redis_match:

networks:
  default:
    external:
      name: riot_api
