version: '2.3'
services:

  proxy:
    build:
      dockerfile: Dockerfile
      context: services/proxy
    container_name: $(COMPOSE_PROJECT_NAME)_proxy
    environment:
      - SERVER=${SERVER}
    env_file:
      - secrets.env
    restart: always
    volumes:
        - ./logs/:/project/logs/

  league_updater:
    build:
      dockerfile: Dockerfile
      context: services/league_updater
    container_name: $(COMPOSE_PROJECT_NAME)_league_updater
    environment:
      - SERVER=${SERVER}
      - UPDATE_INTERVAL=${UPDATE_INTERVAL}
      - BUFFER=${LEAGUE_BUFFER}
    external_links:
      - riotapi_rabbitmq:rabbitmq
    links:
      - proxy:proxy
    depends_on:
      - rabbitmq
    restart: always

  summoner_id_updater:
    build:
      dockerfile: Dockerfile
      context: services/summoner_id_updater
    container_name: $(COMPOSE_PROJECT_NAME)_summoner_id_updater
    environment:
      - SERVER=${SERVER}
      - BUFFER=${SUMMONER_ID_BUFFER}
    links:
      - redis_summoner_id:redis
      - proxy:proxy
    external_links:
      - riotapi_rabbitmq:rabbitmq
    depends_on:
      - redis_summoner_id
      - rabbitmq
    restart: always

  redis_summoner_id:
    build:
      context: databases/redis
      dockerfile: Dockerfile
    container_name: $(COMPOSE_PROJECT_NAME)_redis_summoner_id
    restart: always

  match_history_updater:
    build:
      dockerfile: Dockerfile
      context: services/match_history_updater
    container_name: $(COMPOSE_PROJECT_NAME)_match_history_updater
    environment:
      - SERVER=${SERVER}
      - BUFFER=${MATCH_HISTORY_BUFFER}
      - MATCHES_TO_UPDATE=${MATCHES_TO_UPDATE}
    links:
      - redis_match_history:redis
      - proxy:proxy
    external_links:
      - riotapi_rabbitmq:rabbitmq
    depends_on:
      - redis_match_history
      - rabbitmq
    restart: always

  redis_match_history:
    build:
      context: databases/redis
      dockerfile: Dockerfile
    container_name: $(COMPOSE_PROJECT_NAME)_redis_match_history
    restart: always

  match_updater:
    build:
      dockerfile: Dockerfile
      context: services/match_updater
    container_name: $(COMPOSE_PROJECT_NAME)_match_updater
    environment:
      - SERVER=${SERVER}
      - BUFFER=${MATCH_BUFFER}
    links:
      - redis_match:redis
      - proxy:proxy
    external_links:
      - riotapi_rabbitmq:rabbitmq
    depends_on:
      - redis_match
      - rabbitmq
    restart: always

  redis_match:
    build:
      context: databases/redis
      dockerfile: Dockerfile
    container_name: $(COMPOSE_PROJECT_NAME)_redis_match
    restart: always

  db_worker:
    build:
      dockerfile: Dockerfile
      context: services/db_worker/
    container_name: $(COMPOSE_PROJECT_NAME)_db_worker
    environment:
      - SERVER=${SERVER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
    external_links:
      - riotapi_postgres:postres
      - riotapi_rabbitmq:rabbitmq
    depends_on:
      - rabbitmq
      - postgres
    restart: always

volumes:
  redis_summoner:
    name: ${SERVER}_redis_summoner
  redis_match_history:
    name: ${SERVER}_redis_match_history
  redis_match:
    name: ${SERVER}_redis_match

networks:
  default:
    external:
      name: riot_api
