version: '2.3'
services:
### Services

  league_rankings:
    hostname: league_rankings
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/league_rankings
    environment:
      - SERVER=${SERVER}
      - UPDATE_INTERVAL=1
      - WORKER=5
    links:
      - persistant_db:postgres
    restart: always
    volumes:
      - ranking_progress:/project/configs/

  summoner_ids: # SI
    hostname: summoner_ids
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/summoner_ids
    environment:
      - SERVER=${SERVER}
      - WORKER=35
      - MAX_TASK_BUFFER=1000
      - STREAM=SUMMONER
      - LOGGING=${LOGGING}
    volumes:
      - ./sqlite/:/project/sqlite/
      - /backup
    external_links:
      - lightshield_rabbitmq:rabbitmq
    restart: always

  match_history:  # MH
    hostname: match_history
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/match_history
    environment:
      - SERVER=${SERVER}
      - WORKER=10
      - MATCHES_TO_UPDATE=10
      - TIME_LIMIT=1595401200
      - STREAM=HISTORY
    volumes:
      - ./sqlite/:/project/sqlite/
      - /backup
    links:
      - persistant_db:postgres
    external_links:
      - lightshield_rabbitmq:rabbitmq
    restart: always

  match_details:  # MD
    hostname: match_details
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/match_details
    environment:
      - SERVER=${SERVER}
      - WORKER=45
      - MAX_TASK_BUFFER=1000
      - STREAM=DETAILS
    volumes:
      - /backup
    links:
      - persistant_db:postgres
    external_links:
      - lightshield_rabbitmq:rabbitmq
    restart: always

  processor_match:
    build:
      dockerfile: Dockerfile
      context: services/processor_match
    environment:
      - SERVER=${SERVER}
      - STREAM="placeholder"
      - MAX_TASK_BUFFER=111
    external_links:
      - lightshield_rabbitmq:rabbitmq
    links:
      - persistant_db:postgres
    volumes:
      - ./lol_dto:/project/lol_dto
    restart: always
    logging:
      driver: "json-file"
      options:
       max-file: "5"
       max-size: "10m"

  processor_summoner:
    build:
      dockerfile: Dockerfile
      context: services/processor_summoner
    environment:
      - SERVER=${SERVER}
    external_links:
      - lightshield_rabbitmq:rabbitmq
    links:
      - persistant_db:postgres
    volumes:
      - ./lol_dto:/project/lol_dto
    restart: always
    logging:
      driver: "json-file"
      options:
       max-file: "5"
       max-size: "10m"

  persistant_db:
    container_name: ${COMPOSE_PROJECT_NAME}_persistant_db
    build:
      context: postgres
      dockerfile: Dockerfile
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always

volumes:
  postgres:
    name: ${SERVER}_lightshield_persistent
  ranking_progress:
    name: ${SERVER}_ranking_progress


networks:
  default:
    external:
      name: lightshield
