version: '2.3'
services:

  proxy:
    build:
      dockerfile: Dockerfile
      context: services/proxy
    container_name: ${COMPOSE_PROJECT_NAME}_proxy
    environment:
      - SERVER=${SERVER}
    env_file:
      - secrets.env
    restart: always
    volumes:
        - ./logs/:/project/logs/
        - ./configs/:/project/configs/

### Services

  league_rankings:
    hostname: league_rankings
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/league_rankings
    environment:
      - SERVER=${SERVER}
      - UPDATE_INTERVAL=1
      - WORKER=5
      - REQUIRED_SUBSCRIBER=SI
    links:
      - proxy:proxy
      - league_rankings_redis:redis
    restart: always
    volumes:
      - ./sqlite/:/project/sqlite/
      - ./configs/:/project/configs/

  summoner_ids:  # SI
    hostname: summoner_ids
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/summoner_ids
    environment:
      - SERVER=${SERVER}
      - WORKER=35
      - REQUIRED_SUBSCRIBER=MH,SD
      - MAX_TASK_BUFFER=1000
    volumes:
      - ./sqlite/:/project/sqlite/
    links:
      - summoner_ids_redis:redis
      - proxy:proxy
      - league_rankings:provider
    restart: always

  match_history:  # MH
    hostname: match_history
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/match_history
    environment:
      - SERVER=${SERVER}
      - WORKER=10
      - MATCHES_TO_UPDATE=10
      - TIME_LIMIT=1595401200
      - MAX_TASK_BUFFER=1000
      - REQUIRED_SUBSCRIBER=MD
    volumes:
      - ./sqlite/:/project/sqlite/
    links:
      - match_history_redis:redis
      - proxy:proxy
      - summoner_ids:provider
    restart: always

  match_details:  # MD
    hostname: match_details
    mem_limit: 150m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/match_details
    environment:
      - SERVER=${SERVER}
      - WORKER=45
      - MAX_TASK_BUFFER=1000
    volumes:
      - ./sqlite/:/project/sqlite/
    links:
      - match_details_redis:redis
      - proxy:proxy
      - match_history:provider
    external_links:
      - lightshield_postgres:postres
    restart: always

### Database Connector

  database_connector_summoner:
    hostname: database_connector_summoner
    mem_limit: 250m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/database_connector_summoner/
    environment:
      - SERVER=${SERVER}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=db_worker
      - MAX_TASK_BUFFER=1000
    external_links:
      - lightshield_postgres:postres
    links:
      - summoner_ids:provider
      - database_connector_summoner_redis:redis
    restart: always

  database_connector_match_details:
    hostname: database_connector_match_details
    mem_limit: 250m
    cpus: 0.25
    build:
      dockerfile: Dockerfile
      context: services/database_connector_match_details/
    environment:
      - SERVER=${SERVER}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=db_worker
      - MAX_TASK_BUFFER=1000
    external_links:
      - lightshield_postgres:postres
    links:
      - match_details:provider
      - database_connector_match_details_redis:redis
    restart: always


### REDIS Databases

  league_rankings_redis:
    mem_limit: 250m
    cpus: 0.25
    build:
      context: databases/redis
      dockerfile: Dockerfile
    volumes:
      - league_rankings:/data/
    restart: always

  summoner_ids_redis:
    mem_limit: 250m
    cpus: 0.25
    build:
      context: databases/redis
      dockerfile: Dockerfile
    volumes:
        - summoner_ids:/data/
    restart: always

  match_history_redis:
    mem_limit: 250m
    cpus: 0.25
    build:
      context: databases/redis
      dockerfile: Dockerfile
    volumes:
        - match_history:/data/
    restart: always

  match_details_redis:
    mem_limit: 250m
    cpus: 0.25
    build:
      context: databases/redis
      dockerfile: Dockerfile
    volumes:
        - match_details:/data/
    restart: always

  database_connector_summoner_redis:
    mem_limit: 50m
    cpus: 0.1
    build:
      context: databases/redis
      dockerfile: Dockerfile
    volumes:
      - database_connector_summoner:/data/
    restart: always

  database_connector_match_details_redis:
    mem_limit: 50m
    cpus: 0.1
    build:
      context: databases/redis
      dockerfile: Dockerfile
    volumes:
      - database_connector_match_details:/data/
    restart: always

volumes:
  league_rankings:
    name: ${SERVER}_league_rankings
  summoner_ids:
    name: ${SERVER}_summoner_ids
  match_history:
    name: ${SERVER}_match_history
  match_details:
    name: ${SERVER}_match_details
  database_connector_summoner:
    name: ${SERVER}_database_connector_summoner
  database_connector_match_details:
    name: ${SERVER}_database_connector_match_details

networks:
  default:
    external:
      name: lightshield
