version: '3.7'
services:
  ### Services

  base_image:
    build:
      dockerfile: Dockerfile
      context: services/base
    image: lightshield/base_image:${TAG}
    entrypoint: ['ls']

  league_ranking:
    hostname: league_rankings
    build:
      dockerfile: Dockerfile
      context: services/league_rankings
    image: lightshield/lightshield_league_ranking:${TAG}
    environment:
      - SERVER=${SERVER}
      - UPDATE_INTERVAL=1
      - WORKER=5
    env_file:
      - secrets.env
    restart: always
    volumes:
      - ranking_progress:/project/configs/

  summoner_id_manager:
    hostname: summoner_ids
    build:
      dockerfile: Dockerfile
      context: services/summoner_ids_manager
    image: lightshield/lightshield_summoner_id_manager:${TAG}
    environment:
      - SERVER=${SERVER}
    env_file:
      - secrets.env

  summoner_id: # SI
    hostname: summoner_ids
    build:
      dockerfile: Dockerfile
      context: services/summoner_ids
    image: lightshield/lightshield_summoner_id:${TAG}
    environment:
      - SERVER=${SERVER}
    env_file:
      - secrets.env
    restart: always

  match_history_manager:
    hostname: match_history
    environment:
      - MIN_MATCHES=20
      - SERVER=${SERVER}
    build:
      dockerfile: Dockerfile
      context: services/match_history_manager
    image: lightshield/lightshield_match_history_manager:${TAG}
    env_file:
      - secrets.env

  match_history: # MH
    hostname: match_history
    build:
      dockerfile: Dockerfile
      context: services/match_history
    image: lightshield/lightshield_match_history:${TAG}
    environment:
      - SERVER=${SERVER}
      - QUEUES=420
    restart: always
    env_file:
      - secrets.env

  match_details_manager:
    hostname: match_details
    build:
      dockerfile: Dockerfile
      context: services/match_details_manager
    image: lightshield/lightshield_match_details_manager:${TAG}
    environment:
      - LIMIT=5000
      - SERVER=${SERVER}
    env_file:
      - secrets.env

  match_details: # MH
    hostname: match_details
    build:
      dockerfile: Dockerfile
      context: services/match_details
    image: lightshield/lightshield_match_details:${TAG}
    environment:
      - SERVER=${SERVER}
      - QUEUES=420
      - BATCH_SIZE=30
    restart: always
    env_file:
      - secrets.env

volumes:
  ranking_progress:
    name: ${SERVER}_ranking_progress

networks:
  default:
    external:
      name: lightshield
