version: '3.7'
services:

  redis:
    build:
      dockerfile: Dockerfile
      context: redis
    networks:
      default:
        aliases:
          - redis
    ports:
      - 6379:6379
    restart: always
    environment:
      - "LOG_LEVEL=debug"

networks:
  default:
    external:
      name: lightshield
