version: '3.7'
services:
  ### Databases
  buffer_db:
    image: redis:6.0
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis:/data
    networks:
      default:
        aliases:
          - redis
      lightshield:
        aliases:
          - redis
    restart: always

  proxy:
    image: lightshield/proxy:latest
    networks:
      aliases:
        - proxy
    restart: always
    env_file:
      - secrets.env
    logging:
      driver: "json-file"
      options:
       max-file: "5"
       max-size: "10m"

volumes:
  redis:
    name: lightshield_buffer

networks:
  lightshield:
    external: true
  default:
    external:
      name: lightshield

x-deactivated:
  status_page:
    image: lightshield.dev:5000/lightshield_status_page:latest
    build:
      dockerfile: Dockerfile
      context: global/status_page/backend
    restart: always
    environment:
      - SERVER=NA1,EUW1,KR
    env_file:
      - secrets.env
    ports:
      - 8003:8000
