version: 1.0

database: crate

connections:
  crate:
    host: cratedb
    port: 5432
    user: crate
    schema: lightshield # Crate doesnt have databases
    password_env: CRATE_PASSWORD
  postgres:
    host: host.docker.internal
    port: 5432
    user: postgres
    database: lightshield
    password_env: POSTGRES_PASSWORD
  proxy:
    host: proxy
    port: 8888
    protocol: http
  rabbitmq:
    host: rabbitmq
    port: 5672
    user: user
    password_env: RABBITMQ_PASSWORD

platforms:

services:
  match_history:
    type:
    queue: 420
