version: '3'
services:

  rabbitmq:
    container_name: rabbitmq
    image: launcher.gcr.io/google/rabbitmq3
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
      - '25672:25672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  proxy:
    container_name: proxy
    build:
      dockerfile: Dockerfile
      context: proxy
    volumes:
        - ./config.json:/project/config.json:ro
    environment:
      - SERVER=EUW1
    restart: always

  league_updater:
    container_name: league_updater
    build:
      dockerfile: Dockerfile
      context: league_updater
    links:
      - rabbitmq:rabbitmq
      - proxy:proxy
    restart: always
    volumes:
        - ./config.json:/project/config.json:ro
    environment:
      - SERVER=EUW1

  summoner_id_updater:
    container_name: summoner_id_updater
    build:
      dockerfile: Dockerfile
      context: summoner_id_updater
    links:
      - proxy:proxy
      - redis:redis
    restart: always
    volumes:
        - ./config.json:/project/config.json:ro
    environment:
      - SERVER=EUW1

  redis_summoner_id:
    container_name: redis_summoner_id
    image: redis
    volumes:
      - ./redis/redis.conf:/user/local/etc/redis/redis.conf
      - redis_summoner:/data/


  playerdata:
    container_name: playerdata
    build:
      dockerfile: playerdata/Dockerfile
      context: .
    volumes:
      - playerdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
        - 127.0.0.1:5432:5432

  match_history_updater:
    container_name: match_history_updater
    build:
      dockerfile: Dockerfile
      context: match_history_updater
    links:
      - playerdata:playerdata
      - proxy:proxy
    restart: always
    volumes:
        - ./config.json:/project/config.json:ro
    depends_on:
      - playerdata
    environment:
      - SERVER=EUW1


volumes:
  redis_summoner:
  rabbitmq:
  playerdata:
