version: '3'
services:

  proxy_euw:
    container_name: proxy_euw
    build:
      dockerfile: Dockerfile
      context: proxy
    environment:
      - SERVER=EUW1
    restart: always

  proxy_na:
    container_name: proxy_na
    build:
      dockerfile: Dockerfile
      context: proxy
    environment:
      - SERVER=NA1
    restart: always

  proxy_kr:
    container_name: proxy_kr
    build:
      dockerfile: Dockerfile
      context: proxy
    environment:
      - SERVER=KR
    restart: always

  playerdata:
    container_name: playerdata
    build:
      dockerfile: playerdata/Dockerfile
      context: .
    volumes:
      - playerdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
        - 127.0.0.1:5432:5432

  league_updater_euw:
    container_name: league_updater_euw
    build:
      dockerfile: league_updater/Dockerfile
      context: .
    links:
      - playerdata:playerdata
      - proxy_euw:proxy
    restart: always
    depends_on:
      - playerdata
      - proxy_euw
    environment:
      - SERVER=EUW1

  league_updater_na:
    container_name: league_updater_na
    build:
      dockerfile: league_updater/Dockerfile
      context: .
    links:
      - playerdata:playerdata
      - proxy_na:proxy
    restart: always
    depends_on:
      - playerdata
      - proxy_na
    environment:
      - SERVER=NA1

  league_updater_kr:
    container_name: league_updater_kr
    build:
      dockerfile: league_updater/Dockerfile
      context: .
    links:
      - playerdata:playerdata
      - proxy_kr:proxy
    restart: always
    depends_on:
      - playerdata
      - proxy_kr
    environment:
      - SERVER=KR

  summoner_id_updater_euw:
    container_name: summoner_id_updater_euw
    build:
      dockerfile: summoner_id_updater/Dockerfile
      context: .
    links:
      - playerdata:playerdata
      - proxy_euw:proxy
    restart: always
    depends_on:
      - playerdata
      - proxy_euw
    environment:
      - SERVER=EUW1

  summoner_id_updater_na:
    container_name: summoner_id_updater_na
    build:
      dockerfile: summoner_id_updater/Dockerfile
      context: .
    links:
      - playerdata:playerdata
      - proxy_na:proxy
    restart: always
    depends_on:
      - playerdata
      - proxy_na
    environment:
      - SERVER=NA1

  summoner_id_updater_kr:
    container_name: summoner_id_updater_kr
    build:
      dockerfile: summoner_id_updater/Dockerfile
      context: .
    links:
      - playerdata:playerdata
      - proxy_kr:proxy
    restart: always
    depends_on:
      - playerdata
      - proxy_kr
    environment:
      - SERVER=KR

volumes:
  playerdata:
