version: '2.3'
services:

  manager:
    container_name: manager
    build:
      context: manager
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./secrets.json:/project/secrets.json
      - ./manager/config.json:/project/config.json
    ports:
      - 8765:8765

  rabbitmq:
    build:
      context: rabbitmq
      dockerfile: Dockerfile

  proxy:
    build:
      dockerfile: Dockerfile
      context: services/proxy

  league_updater:
    build:
      dockerfile: Dockerfile
      context: services/league_updater


  summoner_id_updater:
    build:
      dockerfile: Dockerfile
      context: services/summoner_id_updater


  redis_summoner_id:
    build:
      context: databases/redis
      dockerfile: Dockerfile


  match_history_updater:
    build:
      dockerfile: Dockerfile
      context: services/match_history_updater

  redis_match_history:
    build:
      context: databases/redis
      dockerfile: Dockerfile

  match_updater:
    build:
      dockerfile: Dockerfile
      context: services/match_updater

  redis_match:
    build:
      context: databases/redis
      dockerfile: Dockerfile

  db_worker:
    build:
      dockerfile: Dockerfile
      context: services/db_worker/

  postgres:
    cpus: 1
    mem_limit: 1g
    container_name: riotapi_postgres
    build:
      dockerfile: Dockerfile
      context: databases/postgres/
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
        - 127.0.0.1:5432:5432


volumes:
  redis_summoner:
  redis_match_history:
  redis_match:
  rabbitmq:
  playerdata:
  postgres:
