version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: launcher.gcr.io/google/rabbitmq3
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: always

  api_component:
    container_name: api_component
    build:
      dockerfile: api_component/Dockerfile
      context: .
    links:
      - rabbitmq:rabbitmq
    restart: always
    depends_on:
      - rabbitmq

  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  league_updater_euw:
    container_name: league_updater_euw
    build:
      dockerfile: league_updater/Dockerfile
      context: .
    links:
      - rabbitmq:rabbitmq
      - postgres:postgres
    restart: always
    environment:
      - SERVER=EUW1
    depends_on:
      - postgres
      - rabbitmq

  league_updater_kr:
    container_name: league_updater_kr
    build:
      dockerfile: league_updater/Dockerfile
      context: .
    links:
      - rabbitmq:rabbitmq
      - postgres:postgres
    restart: always
    environment:
      - SERVER=KR1
    depends_on:
      - postgres
      - rabbitmq

  league_updater_na:
    container_name: league_updater_na
    build:
      dockerfile: league_updater/Dockerfile
      context: .
    links:
      - rabbitmq:rabbitmq
      - postgres:postgres
    restart: always
    environment:
      - SERVER=NA1
    depends_on:
      - postgres
      - rabbitmq

volumes:
  rabbitmq:
  postgres:
