version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: launcher.gcr.io/google/rabbitmq3
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: always

  api_component:
    container_name: api_component
    build:
      dockerfile: api_component/Dockerfile
      context: .
    links:
      - rabbitmq:rabbitmq
    restart: always
    depends_on:
      - rabbitmq

  playerdata:
    container_name: playerdata
    build:
      dockerfile: playerdata/Dockerfile
      context: .
    volumes:
      - playerdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
        - 127.0.0.1:5432:5432

  league_updater_euw:
    container_name: league_updater_euw
    build:
      dockerfile: league_updater/Dockerfile
      context: .
    links:
      - playerdata:playerdata
    restart: always
    depends_on:
      - playerdata
    environment:
      - SERVER=EUW1

  league_updater_na:
    container_name: league_updater_na
    build:
      dockerfile: league_updater/Dockerfile
      context: .
    links:
      - playerdata:playerdata
    restart: always
    depends_on:
      - playerdata
    environment:
      - SERVER=NA1

  league_updater_kr:
    container_name: league_updater_kr
    build:
      dockerfile: league_updater/Dockerfile
      context: .
    links:
      - playerdata:playerdata
    restart: always
    depends_on:
      - playerdata
    environment:
      - SERVER=KR

  summoner_id_updater_euw:
    container_name: summoner_id_updater_euw
    build:
      dockerfile: summoner_id_updater/Dockerfile
      context: .
    links:
      - playerdata:playerdata
    restart: always
    environment:
      - SERVER=EUW1

  summoner_id_updater_na:
    container_name: summoner_id_updater_na
    build:
      dockerfile: summoner_id_updater/Dockerfile
      context: .
    links:
      - playerdata:playerdata
    restart: always
    environment:
      - SERVER=NA1

  summoner_id_updater_kr:
    container_name: summoner_id_updater_kr
    build:
      dockerfile: summoner_id_updater/Dockerfile
      context: .
    links:
      - playerdata:playerdata
    restart: always
    environment:
      - SERVER=KR

volumes:
  rabbitmq:
  playerdata:
