apiVersion: v1
kind: Service
metadata:
  name: drakebane
spec:
  type: NodePort
  ports:
    - nodePort: 30000
      port: 8000
      targetPort: 8000
  selector:
    app: lightshield
    service: drakebane
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drakebane
  labels:
    service: drakebane
    app: lightshield
spec:
  selector:
    matchLabels:
      name: drakebane
      app: lightshield
  template:
    metadata:
      labels:
        name: drakebane
        app: lightshield
    spec:
      hostname: drakebane
      containers:
        - name: drakebane
          image: lightshield_drakebane:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
