CREATE USER db_worker WITH LOGIN;

CREATE DATABASE data_BR WITH OWNER db_worker;
CREATE DATABASE data_EUNE1 WITH OWNER db_worker;
CREATE DATABASE data_EUW1 WITH OWNER db_worker;
CREATE DATABASE data_JP1 WITH OWNER db_worker;
CREATE DATABASE data_KR WITH OWNER db_worker;
CREATE DATABASE data_LA1 WITH OWNER db_worker;
CREATE DATABASE data_LA2 WITH OWNER db_worker;
CREATE DATABASE data_NA1 WITH OWNER db_worker;
CREATE DATABASE data_OC1 WITH OWNER db_worker;
CREATE DATABASE data_TR1 WITH OWNER db_worker;
CREATE DATABASE data_RU WITH OWNER db_worker;


GRANT ALL PRIVILEGES ON  DATABASE data_BR TO db_worker;
GRANT ALL PRIVILEGES ON  DATABASE data_EUNE1 TO db_worker;
GRANT ALL PRIVILEGES ON  DATABASE data_EUW1 TO db_worker;
GRANT ALL PRIVILEGES ON  DATABASE data_JP1 TO db_worker;
GRANT ALL PRIVILEGES ON  DATABASE data_KR TO db_worker;
GRANT ALL PRIVILEGES ON  DATABASE data_LA1 TO db_worker;
GRANT ALL PRIVILEGES ON  DATABASE data_LA2 TO db_worker;
GRANT ALL PRIVILEGES ON  DATABASE data_NA1 TO db_worker;
GRANT ALL PRIVILEGES ON  DATABASE data_OC1 TO db_worker;
GRANT ALL PRIVILEGES ON  DATABASE data_TR1 TO db_worker;
GRANT ALL PRIVILEGES ON  DATABASE data_RU  TO db_worker;


