# Generated by Django 3.0.5 on 2020-04-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='requested_ids',
            field=models.DateTimeField(null=True),
        ),
    ]
