# Generated by Django 3.0.5 on 2020-04-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_player_requested_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='update_flex',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='update_solo',
            field=models.BooleanField(default=True),
        ),
    ]
