# Generated by Django 3.0.5 on 2020-04-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200418_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='player',
            name='losses_flex',
        ),
        migrations.RemoveField(
            model_name='player',
            name='ranking_flex',
        ),
        migrations.RemoveField(
            model_name='player',
            name='series_flex',
        ),
        migrations.RemoveField(
            model_name='player',
            name='update_flex',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wins_flex',
        ),
    ]
