# Generated by Django 3.0.5 on 2020-04-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200418_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='last',
        ),
        migrations.RemoveField(
            model_name='page',
            name='page',
        ),
        migrations.RemoveField(
            model_name='page',
            name='requested',
        ),
        migrations.AddField(
            model_name='page',
            name='page_limit',
            field=models.IntegerField(default=10),
        ),
    ]
