# Generated by Django 3.0.5 on 2020-04-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagecount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.TextField()),
                ('division', models.TextField()),
                ('queue', models.TextField()),
                ('pages', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=4)),
                ('summoner_id', models.TextField()),
                ('summoner_name', models.TextField(null=True)),
                ('ranking_solo', models.IntegerField(null=True)),
                ('ranking_flex', models.IntegerField(null=True)),
                ('series_solo', models.CharField(max_length=4, null=True)),
                ('series_flex', models.CharField(max_length=4, null=True)),
                ('wins_solo', models.IntegerField(null=True)),
                ('losses_solo', models.IntegerField(null=True)),
                ('wins_flex', models.IntegerField(null=True)),
                ('losses_flex', models.IntegerField(null=True)),
            ],
        ),
    ]
