# Generated by Django 3.0.5 on 2020-04-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.TextField()),
                ('tier', models.TextField()),
                ('division', models.TextField()),
                ('queue', models.TextField()),
                ('page', models.IntegerField()),
                ('last', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pagecount',
        ),
    ]
