# Generated by Django 3.0.5 on 2020-04-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200416_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
