version: 1.0

database: postgres

connections:
  postgres:
    hostname: localhost
    port: 5432
    user: postgres
    database: lightshield
    password_env: POSTGRES_PASSWORD
  crate:
    hostname: localhost
    port: 5433
    user: crate
    schema: lightshield # Crate doesnt have databases
    password_env: CRATE_PASSWORD
  proxy:
    location: 'localhost:8888'
    protocol: http
  rabbitmq:
    host: localhost
    port: 5672

services:
  league_ranking:
    cycle_length: 6
    platforms:
    ranks:

  puuid_collector:

  summoner_tracker:
    update_interval: 12

  match_history:
    min_wait: 1
    history:
      days: 14
      matches: 100
    type:
    queue:
    platforms:

  match_details:
    location:
    regions:

  match_timeline:
    regions:


statics: # Don't change unless changes happen to the API
  enums:
    platforms: [ 'EUW1', 'EUN1', 'TR1', 'RU', 'NA1', 'BR1', 'LA1', 'LA2', 'OC1', 'KR', 'JP1' ]
    regions: [ 'europe', 'americas', 'asia', 'sea' ]
    ranks: [ 'IRON', 'BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'DIAMOND', 'MASTER', 'GRANDMASTER', 'CHALLENGER' ]
    divisions: [ 'I', 'II', 'III', 'IV' ]
  mapping:
    europe: [ "EUW1", "EUN1", "TR1", "RU" ]
    americas: [ "NA1", "BR1", "LA1", "LA2" ]
    asia: [ "KR", "JP1" ]
    sea: [ "OC1" ]
