version: 1.0

database: postgres

connections:
  crate:
    host: localhost
    port: 5433
    user: crate
    schema: lightshield # Crate doesnt have databases
    password_env: CRATE_PASSWORD
  postgres:
    host: localhost
    port: 5432
    user: postgres
    database: lightshield
    password_env: POSTGRES_PASSWORD
  proxy:
    protocol: http
    host: localhost
    port: 8888
  rabbitmq:
    host: localhost
    port: 5672
    user: user
    password_env: RABBITMQ_PASSWORD

platforms:

services: