apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    service: redis
    app: lightshield
spec:
  selector:
    matchLabels:
      name: redis
      app: lightshield
  template:
    metadata:
      labels:
        name: redis
        app: lightshield
    spec:
      hostname: redis
      containers:
        - name: redis
          image: lightshield_redis:latest
          imagePullPolicy: Never
